export const GETREQUEST = "GET_REQUEST";
export const GETREQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GETPOST_SUCCESS = "GET_POST_SUCCESS";
export const GETREQUEST_FAILURE = "GET_REQUEST_FAILURE";

